server:
  port: 8088

spring:
  application:
    name: BellCatShopManagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Binla
    password: admin54736
    url: jdbc:mysql://47.98.159.221:3306/BCS?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

mybatis:
  mapperLocations: classpath:/mapper/*.xml

logging:
  config: classpath:log4j2.xml
