server:
  port: 8088

spring:
  application:
    name: BellCatShopManagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxx
    password: xxxx
    url: jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/xxxx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

mybatis:
  mapperLocations: classpath:/mapper/*.xml

logging:
  config: classpath:log4j2.xml
