server:
  port: 8088

spring:
  application:
    name: BellCatShopManagement

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxxxxx
    password: xxxxxx
    url: jdbc:mysql://000.000.000.000:0000/BCS?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8

mybatis:
  mapperLocations: classpath:/mapper/*.xml

logging:
  config: classpath:log4j2.xml
